<a href="https://colab.research.google.com/github/divyanavghare64-jpg/Data-Analytics-Lab/blob/main/Optional_task_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Load Dataset
df = pd.read_csv("insurance.csv")
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [3]:
# Encode Categorical Variables

le = LabelEncoder()

df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])

df.head()

   age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [5]:
# Define Features and Target

X = df.drop("expenses", axis=1)
y = df["expenses"]

print(X.head())
print(y.head())

   age  sex   bmi  children  smoker  region
0   19    0  27.9         0       1       3
1   18    1  33.8         1       0       2
2   28    1  33.0         3       0       2
3   33    1  22.7         0       0       1
4   32    1  28.9         0       0       1
0    16884.92
1     1725.55
2     4449.46
3    21984.47
4     3866.86
Name: expenses, dtype: float64

In [6]:
# Splite Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (1070, 6)
Testing Data: (268, 6)

In [7]:
# Train the ML Model

model = LinearRegression()
model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [8]:
# Make Predictions

y_pred = model.predict(X_test)

print(y_pred[:10])

[ 8931.64285422  7108.65837503 36911.24588592  9492.1867315
 27005.51458817 10792.51319722   219.4619664  16940.94699877
  1057.14434333 11271.11976436]

In [9]:
#  Evaluate the Model

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 4186.940106317013
MSE: 33639075.08997808
R2 Score: 0.7833214205203847